### ISSUE TITLE
Error while importing sbt project

### ISSUE THREAD

**Issue by HarmlessEvil** [Chymyst/helloworld#1]
I am following your [tutorial](https://www.youtube.com/watch?v=6sBadc69UtM) on YouTube and tried to run your project. (I mean, IntelliJ started to dump sbt project)

After 10 minutes of waiting I got the following error (I deleted stack trace as it's too long):

Error while importing sbt project:
<... List of success downloads ...>
Getting Scala 2.10.6 (for sbt)...
downloading https://repo1.maven.org/maven2/org/scala-lang/jline/2.10.6/jline-2.10.6.jar ...
[SUCCESSFUL ] org.scala-lang#jline;2.10.6!jline.jar (2398ms)
:: retrieving :: org.scala-sbt#boot-scala
confs: [default]
5 artifacts copied, 0 already retrieved (24494kB/355ms)
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
<... Stack trace ...>
[error] scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

**Comment by winitzki** [comment]
Not sure what project you were importing, with which version of IntelliJ, which version of Scala and SBT, and whether this error is transient or persistent when you reopen IntelliJ.

**Comment by HarmlessEvil** [comment]
1. Project, that I am importing: a fresh `git clone https://github.com/Chymyst/helloworld`
2. IntelliJ IDEA 2018.3.3 (Ultimate Edition) Build #IU-183.5153.38, built on January 10, 2019
3. Scala 2.12.8
4. SBT 0.13 (bundled into IntelliJ IDEA)

The error is persistent, it prevents me from running the project at all 😥

**Comment by winitzki** [comment]
Did you try running `sbt compile` on the command line, rather than in IntelliJ? I find that errors while importing projects are more difficult to understand in IntelliJ than on the command line.

I just checked right now that I can open and run the `Chymyst/helloworld` project in IntelliJ 2018.3.3 (Community edition) with no errors...

**Comment by HarmlessEvil** [comment]
From the project directory I ran `sbt compile`
Another error, stack trace fit exactly to one screen)
![default](https://user-images.githubusercontent.com/23358195/51434725-54445980-1cb3-11e9-84a1-71d05b1d63e7.png)

I should notice, that I am novice in Scala and it's pretty difficult to get familiar with SBT. Maybe I should double check something? 🤔 

UPD: I can import clean projects from SBT (when I create a new project in IntelliJ) and everything works pretty fine - thus I mean, that SBT should be configured correclty, the problem occurs only here(

**Comment by winitzki** [comment]
What is the version of Java you are using?

Your error was discussed https://stackoverflow.com/questions/50559843/scala-project-using-sbt-throws-nullpointerexception and https://github.com/sbt/sbt/issues/4259 where it says,

`It looks like you're using JDK 9 or 10. If so please use SBT 0.13.17.`

Maybe that's your issue?

I'm still using Oracle JDK 8.

**Comment by HarmlessEvil** [comment]
Thanks, it worked!
